---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  annotations: {}
  labels:
    name: chuck-norris
  name: chuck-norris
  namespace: chuck-norris
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chuck-norris-role
subjects:
- kind: ServiceAccount
  name: chuck-norris
  namespace: chuck-norris
